%YAML:1.0

imu: 1         
num_of_cam: 2  

imu_topic: "/imu0"
image0_topic: "/oak/left/image_rect"
image1_topic: "/oak/right/image_rect"
output_path: "~/output/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"

image_width: 640
image_height: 480

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.03557433, -0.01678714, 0.99922603, 0.06636409,
          -0.99935446, -0.00561302, 0.0354846, 0.03770078,
          0.005013, -0.99984333, -0.01697598, 0.02800269,
          0.0, 0.0, 0.0, 1.0]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.04363218, -0.01555458, 0.99892657, 0.06964087,
          -0.99904723, 0.00024828, 0.04364132, -0.03732767,
          -0.00092683, -0.99987899, -0.01552893, 0.02793308,
          0.0, 0.0, 0.0, 1.0]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 100            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 0                 # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
flow_back: 0            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 4   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

acc_n: 0.055437171645025325
gyr_n: 0.0012346084399517119
acc_w: 0.000981
gyr_w: 0.000349
g_norm: 9.81007

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.05544      # accelerometer measurement noise standard deviation. 
gyr_n: 0.001235     # gyroscope measurement noise standard deviation.     
acc_w: 0.0009810    # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0003490    # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: -0.0007835763358029035          # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
